apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  # ReadWriteMany
  # ReadWriteOnce
  # ReadOnlyOnce
  # Many: accessible by multiple containers
  accessModes:
    - ReadWriteOnce
  # with local storageClass by default
  # https://kubernetes.io/docs/concepts/storage/storage-classes/
